--KH1
CREATE PROCEDURE KH_XEM_TATCA_DN
AS 
SELECT MADN, TEN_DN,THANH_PHO,QUAN,DIA_CHI
FROM DOANH_NGHIEP
GO

--KH2 
CREATE OR ALTER PROCEDURE KH_XEM_SP_THEO_MADN
( @MADN CHAR(10)
)
AS 
SELECT SP.MA_SP,SP.TEN_SP,SP.GIA,SP.SO_LUONG,SP.MO_TA
FROM  DOANH_NGHIEP  DN JOIN CHI_NHANH  CN
ON (DN.MADN=CN.MADN) 
JOIN CHINHANH_SANPHAM CN_SP
ON (CN.MA_CN=CN_SP.MA_CN)
JOIN SAN_PHAM SP
ON (CN_SP.MA_SP=SP.MA_SP)
WHERE DN.MADN=@MADN
GO



--KH3
CREATE OR ALTER PROCEDURE KH_TIM_SP_THEO_TENDN_TENSP
(
@TENDN NVARCHAR(50),
@TENSP NVARCHAR(50)
)
AS 
SELECT SP.MA_SP,SP.TEN_SP,SP.GIA,SP.SO_LUONG,SP.MO_TA
FROM  DOANH_NGHIEP  DN JOIN CHI_NHANH  CN
ON (DN.MADN=CN.MADN) 
JOIN CHINHANH_SANPHAM CN_SP
ON (CN.MA_CN=CN_SP.MA_CN)
JOIN SAN_PHAM SP
ON (CN_SP.MA_SP=SP.MA_SP)
WHERE DN.TEN_DN LIKE @TENDN 
AND SP.TEN_SP LIKE @TENSP
GO


 --KH4
 CREATE PROCEDURE TIMDN_THEO_TEN_QUAN  
 (
 @TEN NVARCHAR(50),
 @QUAN NVARCHAR(50)
 )
 AS 
 SELECT * 
 FROM DOANH_NGHIEP DN
 WHERE DN.TEN_DN LIKE  @TEN 
 AND DN.QUAN LIKE @QUAN

 GO


 --KH5

 CREATE OR ALTER PROCEDURE KH_THONGKE_DN_SP
(
@TENDN NVARCHAR(50)
)
AS 
SELECT SP.MA_SP,SP.TEN_SP,SP.GIA,SP.SO_LUONG
FROM  DOANH_NGHIEP  DN JOIN CHI_NHANH  CN
ON (DN.MADN=CN.MADN) 
JOIN CHINHANH_SANPHAM CN_SP
ON (CN.MA_CN=CN_SP.MA_CN)
JOIN SAN_PHAM SP
ON (CN_SP.MA_SP=SP.MA_SP)
WHERE DN.TEN_DN LIKE @TENDN 
ORDER BY SP.SO_LUONG DESC
GO

 --KH6
CREATE OR ALTER PROCEDURE KH_MUA_HANG
( 
@MADON CHAR(10),
@MAKV CHAR(10),
@MADN CHAR(10),
@MAKH CHAR(10),
@HINHTHUCTHANHTOAN NVARCHAR(50)
)
AS 
INSERT INTO DON_DAT_HANG
VALUES (@MADON,@MAKV,@MADN,NULL,@MAKH,NULL,N'CHỜ XÁC NHẬN',20000,10000,10000,@HINHTHUCTHANHTOAN)
GO

 --TX1

 CREATE PROCEDURE TX_XEM_DH
 AS 
 SELECT * FROM DON_DAT_HANG
 WHERE MA_TX=NULL
 GO

 CREATE OR ALTER PROCEDURE TX_NHAN_DH
 (
 @MATX CHAR(10),
 @MADH CHAR(10)
 )
 AS 
 IF(@MATX IS NOT NULL AND @MADH IS NOT NULL )
   BEGIN 
      UPDATE DON_DAT_HANG
      SET MA_TX=@MATX
      WHERE MA_DON=@MADH
	END
 ELSE  
	 PRINT N'VUI LONG NHAP DAY DU THONG TIN'
GO


 --DN3
 CREATE PROCEDURE CAPNHAP_GIA_TEN_SP
 (
@MASP  CHAR(10),
@GIA INT,
@TENSP NVARCHAR(50)
 )
 AS  UPDATE SAN_PHAM 
 SET GIA=@GIA,
 TEN_SP=@TENSP
 WHERE MA_SP=@MASP


 --DN4
 GO 

 CREATE PROCEDURE THEM_SP
 (
 @MASP CHAR(10),
 @TENSP NVARCHAR(50),
@GIA INT,
@SOLUONG INT,
@MOTA NVARCHAR(100)
 )
 AS 
 IF (@MASP IS NOT NULL )
 BEGIN 
  INSERT INTO SAN_PHAM VALUES( @MASP,@TENSP,@GIA,@SOLUONG,@MOTA)
 END

 GO


 --QT1
 CREATE OR ALTER PROCEDURE AD_XEM_DN
 AS 
 SELECT * 
 FROM DOANH_NGHIEP
 GO

 EXEC AD_XEM_DN
 GO
 --QT2
 
 CREATE OR ALTER PROCEDURE CAPNHAT_DN
 (
 @MADN CHAR(10),
 @QUAN  NVARCHAR(50)
 )
 AS UPDATE DOANH_NGHIEP 
 SET QUAN=@QUAN
 WHERE MADN=@MADN

 GO