
--T1 : KHÁCH HÀNG TÌM SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR
--T2 : DOANH NGHIỆP CẬP NHẬT SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR THÀNH 1TR1
--T1 : KHÁCH HÀNG TÌM LẠI SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR

BEGIN TRANSACTION
SELECT * FROM SAN_PHAM WHERE GIA=999999
-- Do Some work
WAITFOR DELAY '00:00:05'
SELECT * FROM SAN_PHAM WHERE GIA<1000000
COMMIT TRANSACTION
GO


-- CẬP NHẬT LẠI GIÁ ĐỂ DEMO CHO NHỮNG LẦN SAU
UPDATE SAN_PHAM 
SET GIA =999999
WHERE GIA<1200000
