--T1 : KHÁCH HÀNG TÌM SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR
--T2 : DOANH NGHIỆP CẬP NHẬT SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR THÀNH 1TR1
--T1 : KHÁCH HÀNG TÌM LẠI SẢN PHẨM CÓ GIÁ BÉ HƠN 1TR

UPDATE  SAN_PHAM
SET GIA =1100000
WHERE GIA<1000000

