--T1: Doanh nghiệp 'DN71715083' xem số lượng đơn hàng của mình.
--T2: Thêm đơn đặt hàng mới.

BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SELECT COUNT( DDH.MA_DON)
	FROM DOANH_NGHIEP DN, DON_DAT_HANG DDH
	WHERE DN.MADN = N'DN71715083' AND DDH.MADN = DN.MADN

	WAITFOR DELAY '00:00:05'

	SELECT DDH.MA_DON, DDH.MA_KV, DDH.MA_TX, DDH.MA_KH, DDH.NGAY_LAP, DDH.TINH_TRANG, DDH.TONG_TIEN_, DDH.PHI_SAN_PHAM, DDH.PHI_VAN_CHUYEN, DDH.HINH_THUC_THANH_TOAN
	FROM DOANH_NGHIEP DN, DON_DAT_HANG DDH
	WHERE DN.MADN = N'DN71715083' AND DDH.MADN = DN.MADN
COMMIT TRAN