--T1: Khách hàng xem số lượng các sản phẩm có số lượng = 100 của doanh nghiệp có mã 'DN83267769'
--T2: Doanh nghiệp thêm sản phẩm có số lượng = 100

BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SELECT  COUNT(DISTINCT SP.MA_SP)
	FROM SAN_PHAM SP, DOANH_NGHIEP DN, CHI_NHANH CN, CHINHANH_SANPHAM CNSP 
	WHERE DN.MADN = N'DN83267769' AND SP.SO_LUONG = 100 AND CN.MADN = DN.MADN AND SP.MA_SP = CNSP.MA_SP AND CN.MA_CN = CNSP.MA_CN

	WAITFOR DELAY '00:00:05'

	SELECT  DISTINCT SP.MA_SP, SP.TEN_SP, SP.SO_LUONG
	FROM SAN_PHAM SP, DOANH_NGHIEP DN, CHI_NHANH CN, CHINHANH_SANPHAM CNSP 
	WHERE DN.MADN = N'DN83267769' AND SP.SO_LUONG = 100 AND CN.MADN = DN.MADN AND SP.MA_SP = CNSP.MA_SP AND CN.MA_CN = CNSP.MA_CN
COMMIT TRAN
