--T1: Khách hàng xem số lượng sản phẩm có giá > 10000 của doanh nghiệp
--T2: Doanh nghiệp cập nhật giá sản phẩm.

BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SELECT  COUNT(DISTINCT SP.MA_SP)
	FROM SAN_PHAM SP, DOANH_NGHIEP DN, CHI_NHANH CN, CHINHANH_SANPHAM CNSP 
	WHERE DN.MADN = N'DN26568168' AND SP.GIA > 10000 AND CN.MADN = DN.MADN AND SP.MA_SP = CNSP.MA_SP AND CN.MA_CN = CNSP.MA_CN

	WAITFOR DELAY '00:00:05'

	SELECT  DISTINCT SP.MA_SP, SP.TEN_SP, SP.SO_LUONG, SP.GIA
	FROM SAN_PHAM SP, DOANH_NGHIEP DN, CHI_NHANH CN, CHINHANH_SANPHAM CNSP 
	WHERE DN.MADN = N'DN26568168' AND SP.GIA > 10000 AND CN.MADN = DN.MADN AND SP.MA_SP = CNSP.MA_SP AND CN.MA_CN = CNSP.MA_CN
COMMIT TRAN